# Generated by Django 5.2.10 on 2026-01-29 03:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="birth_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="birth_month",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="middle_initial",
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name="person",
            name="photo",
            field=models.FileField(blank=True, null=True, upload_to="people/photos/"),
        ),
        migrations.AddField(
            model_name="person",
            name="street_address",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
