# Generated by Django 5.2.10 on 2026-01-31 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_person_birth_day_person_birth_month_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="family",
            options={"verbose_name_plural": "Families"},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "Person", "verbose_name_plural": "People"},
        ),
        migrations.AddField(
            model_name="person",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
