# Generated by Django 5.2.10 on 2026-02-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_systemsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="confidential_notes",
            field=models.TextField(blank=True),
        ),
    ]
