# Generated by Django 5.2.10 on 2026-02-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_seed_admin_skin_setting"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
