# Generated by Django 5.2.10 on 2026-07-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_seed_printer_profile_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="people/photos/",
                verbose_name="Profile photo",
            ),
        ),
    ]
