# Generated by Django 5.2.10 on 2026-07-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="label",
            field=models.CharField(default="Sabbath Service", max_length=100),
        ),
    ]
