# Generated by Django 5.2.10 on 2026-07-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_service_sabbath_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="kiosk_submission_token",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True, unique=True
            ),
        ),
    ]
