# Generated by Django 5.2.10 on 2026-09-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_person_kiosk_submission_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="automatic_date",
            field=models.DateField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
